export enum ManageFavorite {
  ADD_FAVORITE = 'ADD_FAVORITE',
  REMOVE_FAVORITE = 'REMOVE_FAVORITE',
}

export enum SearchActionType {
  ADD_SEARCHMOVIE = 'ADD_SEARCHMOVIE',
  REMOVE_SEARCHMOVIE = 'REMOVE_SEARCHMOVIE',
}
